package com.me.drools_poc.drl

import java.io.BufferedReader;
import java.io.File;
import java.nio.file.Files;

import org.apache.commons.csv.CSVFormat;
import org.apache.commons.csv.CSVRecord;

rule "parse file"
	when
		file: File()
	then
		try(BufferedReader reader = Files.newBufferedReader(file.toPath())) {
			final CSVFormat format = CSVFormat.RFC4180.withFirstRecordAsHeader();
			final Iterable<CSVRecord> records = format.parse(reader);
			for(CSVRecord record : records){
				insert(new CSVEntity(record));
			}
		}
end
